---
hero_image: images / team-chooser.png
theme: tolet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Seletor de equipe
description: Faça um programa para dividir os jogadores em duas equipes aleatórias.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
  - 
    title: 'Introduction: '
  - 
    title: Jogadoras
  - 
    title: 'Desafio: Adicionando mais jogadores'
  - 
    title: Jogadores aleatórios
  - 
    title: 'Desafio: Escolhendo para o time B'
  - 
    title: Escolhendo muitos jogadores
  - 
    title: arquivos
  - 
    title: Jogadores ímpares
  - 
    title: 'Desafio: nomes aleatórios de equipes'
  - 
    title: 'Desafio: Armazenar nomes de equipes'
  - 
    title: 'Desafio: mais equipes'
