---
hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Odaberi tim
description: U ovom projektu ćeš naučiti kako kreirati dva nasumična tima koristeći imena igrača sa datog popisa.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
  - 
    title: 'Uvod: '
  - 
    title: Igrači
  - 
    title: 'Izazov: Dodaj još igrača'
  - 
    title: Nasumični igrači
  - 
    title: 'Izazov: Odaberi igrače za tim B'
  - 
    title: Odabir više igrača
  - 
    title: Datoteke
  - 
    title: Neparan broj igrača
  - 
    title: 'Izazov: Nasumična imena timova'
  - 
    title: 'Izazov: Spremanje imena timova'
  - 
    title: 'Izazov: Više timova'
