---
hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Team Wähler
description: Erstelle ein Programm, um die Mitspieler in 2 beliebige Teams aufzuteilen.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: games
technologies: Python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
- title: 'Einleitung: '
  completion: engaged
- title: Mitspieler
- title: 'Aufgabe: Weitere Mitspieler hinzufügen'
- title: Zufällig ausgesuchte Mitspieler
- title: 'Aufgabe: Für Team B wählen'
- title: Viele Mitspieler wählen
- title: Dateien
- title: Ungerade Anzahl an Mitspielern
- title: 'Aufgabe: Zufällige Teamnamen'
- title: 'Aufgabe: Teamnamen speichern'
  completion: internal
- title: 'Aufgabe: Weitere Teams'
