---
hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Seleccionador de equipos
description: Crea un programa para dividir a los jugadores en 2 equipos aleatorios.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
- title: 'Introducción: '
- title: Jugadores
- title: 'Desafío: Añadir más jugadores'
- title: Jugadores aleatorios
  completion:
  - engaged
- title: 'Desafío: Elegir para el equipo B'
- title: Selección de muchos jugadores
- title: Archivos
- title: Jugadores impares
  completion:
  - internal
- title: 'Desafío: Nombra los equipos aleatorios'
- title: 'Desafío: Almacenamiento de los nombres de los equipos'
- title: 'Desafío: Más equipos'
