---
hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: 임의의 팀 배정 프로그램
description: 플레이어를 2 개의 임의의 팀으로 나누는 프로그램을 만듭니다.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
  - 
    title: '들어가며: '
  - 
    title: 플레이어
  - 
    title: '과제: 더 많은 플레이어 추가'
  - 
    title: 임의의 플레이어
    completion:
      - engaged
  - 
    title: '과제: 팀 B에 대한 Code 제작'
  - 
    title: 많은 플레이어 선택
  - 
    title: 파일들
  - 
    title: 홀수 플레이어 취급하기
    completion:
      - internal
  - 
    title: '과제: 임의의 팀 이름'
  - 
    title: '과제: 팀 이름 저장'
  - 
    title: '과제: 더 많은 팀'
