---
hero_image: images / team chooser.png
theme: violett
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Team Chooser
description: Gör ett program för att dela spelare i 2 slumpartade lag.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: spel
technologies: pytonorm
site_areas: projekt
hardware: ''
software: pytonorm
version: 3
last_tested: 2018/04/05
steps:
  - 
    title: 'Introduktion: '
  - 
    title: spelare
  - 
    title: 'Utmaning: Att lägga till fler spelare'
  - 
    title: Slumpmässiga spelare
  - 
    title: 'Utmaning: Välja för lag B'
  - 
    title: Välja massor av spelare
  - 
    title: filer
  - 
    title: Odd spelare
  - 
    title: 'Utmaning: Slumpmässiga lagnamn'
  - 
    title: 'Utmaning: Lagring av lagnamn'
  - 
    title: 'Utmaning: Fler lag'
