---
hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Odaberi tim
description: Napravi program koji nasumično dijeli igrače u dva tima.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
- title: Uvod
  completion: engaged
- title: Igrači
- title: 'Izazov: Dodaj još igrača'
- title: Nasumični igrači
- title: 'Izazov: Odaberi igrača za tim B'
- title: Biranje više igrača
- title: Datoteke
- title: Neparan broj igrača
- title: 'Izazov: Nasumični nazivi timova'
- title: 'Izazov: Čuvanje naziva timova'
  completion: internal
- title: 'Izazov: Više timova'
