hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Team Chooser
description: Crée un programme pour partager plusieurs joueurs aléatoirement en deux équipes.
original_url: https://codeclubprojects.org/en-GB/python/team-chooser
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: 'Introduction'
- title: Joueurs
- title: 'Défi: Ajoute plus de joueurs'
- title: Joueurs aléatoires
- title: "Défi: Choisir pour l'équipe B"
- title: Choisir plein de joueurs
- title: Fichiers
- title: Joueurs impair
- title: "Défi: Nom d'équipe aléatoire"
- title: "Défi: Stock les noms d'équipe"
- title: "Défi: Encore plus d'équipe"

